### ISSUE TITLE
The namespace `Invert.Json' already contains a definition for `JsonExtensions'

### ISSUE THREAD

**Issue by moto2002** [micahosborne/uFrame#11]
Assets/Plugins/uFrame/Invert.Common/JSON.cs(56,25): error CS0101: The namespace `Invert.Json' already contains a definition for `JsonExtensions'

**Comment by micahosborne** [comment]
As it states on the main page.

WE HAVE MOVED TO A NEW ORGANIZATION https://github.com/uFrame

**Comment by micahosborne** [comment]
didn't mean to all caps that.. just copy and pasted from the main page
